### ISSUE TITLE
Research Request - Statewide/District-wide maps/visualizations

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-analyses#1214]
## Research Question

Several people have asked for statewide or district-wide overview and maps of transit service.
  
## How will this research be used?

This information will be used to show a high-level overview of the amount of transit service statewide and in each district which will in turn serve as an invitation to view more detailed information about each agency.

## Stakeholders & End-Users

District 6 Staff:
- Lorena Mendibles
- John Baptista
- Chris Xiong
Gillian

## Metrics

- Map of the "service area" for each transit agency
- List of all transit agencies either statewide or in a district
- High-level stats - Number of agencies, number of stops, number of routes
- Map of all the stops for each transit agency
- Map of the routes for each transit agency

## Data sources

* **Cal-ITP data sources**:
- California Transit Database
- California GTFS data warehouse

* **External data sources**:

- GTFS data downloaded from transit operators

* **Remaining data source questions**:

- Maybe census data would be interesting to show too?

## Deliverables

Some of these questions are already answered on the [Statewide Transit Metrics Dashboard](https://dashboards.calitp.org/dashboard/185-statewide-transit-metrics?tab=9-overall-stats), they should be added in a public-facing manner, potentially to the [GTFS Digest Website](https://gtfs-digest--cal-itp-data-analyses.netlify.app/district_06-fresno).

## Timeline of deliverables

No hard due date.

**Comment by tiffanychu90** [comment]
* [Slack thread](https://cal-itp.slack.com/archives/C02JGRQ4Y9Y/p1724432401368079)
* Questions to resolve: ask Amanda after she's back about this [diff ](https://github.com/cal-itp/data-analyses/commit/e22232dd6b184a65d0c07e404de5b2aa247bd523#diff-2cbed682d0e25de665df83621030963561edc53b679438cec054d9b076fb28ed)
   * Earlier version keeps all the service dates.  There might be something related to not all operators have the most recent date, so filtering on an explicit value loses operators.
   * Is dropping all the dates is desirable? This would keep the combo of `schedule_gtfs_dataset_key - organization_name - NTD columns`, but there's no guarantee this gets us down to 1 operator. For LA Metro, we do have 2 keys with the same name, and we want to keep both rail and bus. But for other operators, we might accidentally keep more rows than we want because their key changes, but organization name doesn't.
   * Also, this keeps the earliest date, based on sorting. We might favor most recent date over earliest date, which would be Mar 2023?

**Comment by evansiroky** [comment]
The district digests look great! There are some missing, such as in #1254, but the overall framework seems made, so I'm closing.
